name: 'Build and push HyperHDR docker'
inputs:
  docker_file:
    required: true    
  docker_tag:
    required: true    
  build_args:
    required: true
  registry_username:
    required: true
  registry_password:
    required: true       
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
      
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v3.6.0

    - name: Install Docker Buildx
      uses: docker/setup-buildx-action@v3.11.1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3.4
      with:
        registry: ghcr.io
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}

    - name: Build & push docker container
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        push: true
        file: ${{ inputs.docker_file }}
        tags: ${{ inputs.docker_tag }}
        build-args: ${{ inputs.build_args }}