name: HyperHdr Docker Builder

on:
  push:
    branches:
      - master

env:
  DEBIAN_TESTING: "bookworm"

jobs:
  Docker:
    name: ${{ matrix.dockerOS }} ${{ matrix.linuxVersion }} ${{ matrix.description }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        architecture: [ x86_64, rpi012-armv6l, rpi34-armv7l, arm-aarch64]
        linuxVersion: [ bullseye, bookworm]
        include:
          - architecture: x86_64
            linuxVersion: "ArchLinux"
            dockerOS: ""
            dockerSource: ""
            description: ArchLinux (x86_64)
            tool: buildArch
            os: Ubuntu-22.04
          - architecture: x86_64
            linuxVersion: "Fedora_38"
            dockerOS: ""
            dockerSource: "fedora:38"
            description: "(x86_64)"
            tool: buildFedora
            os: Ubuntu-22.04            
          - architecture: x86_64
            dockerOS: Ubuntu
            dockerSource: ubuntu
            linuxVersion: jammy
            description: Ubuntu 22.04 LTS (x86_64)
            tool: buildNative
            os: Ubuntu-22.04
          - architecture: x86_64
            dockerOS: Ubuntu
            dockerSource: ubuntu
            linuxVersion: lunar
            description: Ubuntu 23.04 (x86_64)
            tool: buildNative
            os: Ubuntu-22.04
          - architecture: x86_64
            dockerOS: Debian
            dockerSource: debian
            description: (x86_64)
            tool: buildNative
            os: Ubuntu-22.04
          - architecture: rpi012-armv6l
            dockerOS: Debian
            dockerSource: raspberry-pi
            description: (Raspberry Pi ZERO, 1 & 2)
            tool: buildCross
            os: Ubuntu-22.04
          - architecture: rpi34-armv7l
            dockerOS: Debian
            dockerSource: raspberrypi3
            altDockerSource: raspberry-pi
            description: (Raspberry Pi 3 & 4)
            tool: buildCross
            os: Ubuntu-22.04
          - architecture: arm-aarch64
            dockerOS: Debian
            dockerSource: raspberrypi3-64
            description: (ARM aarch64)
            tool: buildCross
            os: Ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker container
        if: matrix.linuxVersion != env.DEBIAN_TESTING || matrix.altDockerSource ==''
        run: |
          docker build -t ghcr.io/awawa-dev/${{ matrix.architecture }}:${{ matrix.linuxVersion }} --build-arg LINUX_VERSION=${{ matrix.linuxVersion }} --build-arg LINUX_ARCHITECTURE=${{ matrix.architecture }} --build-arg DOCKER_SOURCE=${{ matrix.dockerSource }} --build-arg BUILD_DESC="${{ matrix.description }}" -f ${{ matrix.tool }} .

      - name: Build Debian (next version) docker container
        if: matrix.linuxVersion == env.DEBIAN_TESTING && matrix.altDockerSource !=''
        run: |
          docker build -t ghcr.io/awawa-dev/${{ matrix.architecture }}:${{ matrix.linuxVersion }} --build-arg LINUX_VERSION=${{ matrix.linuxVersion }} --build-arg LINUX_ARCHITECTURE=${{ matrix.architecture }} --build-arg DOCKER_SOURCE=${{ matrix.altDockerSource }} --build-arg BUILD_DESC="${{ matrix.description }}" -f ${{ matrix.tool }} .

      - name: Publish to GitHub Container & Package Registry
        run: |
          docker push ghcr.io/awawa-dev/${{ matrix.architecture }}:${{ matrix.linuxVersion }}

