name: HyperHdr Docker Builder

on:
  push:
    branches:
      - testing

env:
  DEBIAN_TESTING: "bookworm"

jobs:
  Docker:
    name: ${{ matrix.dockerOS }} ${{ matrix.linuxVersion }} ${{ matrix.description }}
    runs-on: Ubuntu-22.04
    permissions:
      packages: write    
    strategy:
      matrix:
        architecture: [ x86_64, arm-32bit-armv6l, arm-64bit-aarch64]
        linuxVersion: [ bullseye, bookworm]
        include:
          - architecture: x86_64
            linuxVersion: "ArchLinux"
            dockerOS: ""
            dockerSource: ""
            description: ArchLinux (x86_64)
            tool: buildArch
          - architecture: x86_64
            linuxVersion: "Fedora_40"
            dockerOS: ""
            dockerSource: "fedora:40"
            description: "(x86_64)"
            tool: buildFedora
          - architecture: x86_64
            dockerOS: Ubuntu
            dockerSource: ubuntu
            linuxVersion: jammy
            description: Ubuntu 22.04 LTS (x86_64)
            tool: buildNative
          - architecture: x86_64
            dockerOS: Ubuntu
            dockerSource: ubuntu
            linuxVersion: noble
            description: Ubuntu 24.04 LTS (x86_64)
            tool: buildNative
          - architecture: x86_64
            dockerOS: Debian
            dockerSource: debian
            description: (x86_64)
            tool: buildNative
          - architecture: arm-32bit-armv6l
            dockerOS: Debian
            dockerSource: raspberry-pi
            description: (ARM 32bit armv6l)
            tool: buildCross
          - architecture: arm-64bit-aarch64
            dockerOS: Debian
            dockerSource: raspberrypi3-64
            description: (ARM 64bit aarch64)
            tool: buildCross

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker container
        if: matrix.linuxVersion != env.DEBIAN_TESTING || matrix.altDockerSource ==''
        run: |
          docker build -t ghcr.io/awawa-dev/${{ matrix.architecture }}:${{ matrix.linuxVersion }} --build-arg LINUX_VERSION=${{ matrix.linuxVersion }} --build-arg LINUX_ARCHITECTURE=${{ matrix.architecture }} --build-arg DOCKER_SOURCE=${{ matrix.dockerSource }} --build-arg BUILD_DESC="${{ matrix.description }}" -f ${{ matrix.tool }} .

      - name: Build Debian (next version) docker container
        if: matrix.linuxVersion == env.DEBIAN_TESTING && matrix.altDockerSource !=''
        run: |
          docker build -t ghcr.io/awawa-dev/${{ matrix.architecture }}:${{ matrix.linuxVersion }} --build-arg LINUX_VERSION=${{ matrix.linuxVersion }} --build-arg LINUX_ARCHITECTURE=${{ matrix.architecture }} --build-arg DOCKER_SOURCE=${{ matrix.altDockerSource }} --build-arg BUILD_DESC="${{ matrix.description }}" -f ${{ matrix.tool }} .

      #- name: Publish to GitHub Container & Package Registry
      #  run: |
      #    docker push ghcr.io/awawa-dev/${{ matrix.architecture }}:${{ matrix.linuxVersion }}

