name: HyperHdr Docker Builder

on:
  push:

jobs:
  DevelopmentDockerBuilder:
    name: ghcr.io/awawa-dev/${{ matrix.architecture }}/${{ matrix.distro }}:${{ matrix.distroVersion }}
    runs-on: ${{ matrix.runner }}
    permissions:
      packages: write

    strategy:
      matrix:
        architecture: [ x86_64, armv6l, aarch64]
        distroVersion: [ bullseye, bookworm]
        include:
          - runner: ubuntu-24.04
            architecture: x86_64
            distro: ArchLinux
            dockerSource: library/archlinux:base-devel
            tool: buildArch

          - runner: ubuntu-24.04
            architecture: x86_64
            distro: Fedora
            distroVersion: 42
            tool: buildFedora

          - runner: ubuntu-24.04
            architecture: x86_64
            distro: Ubuntu
            distroVersion: jammy
            tool: buildDebian

          - runner: ubuntu-24.04
            architecture: x86_64
            distro: Ubuntu
            distroVersion: noble
            tool: buildDebian

          - runner: ubuntu-24.04
            architecture: x86_64
            distro: Ubuntu
            distroVersion: noble
            tool: buildDebian
                     
          - runner: ubuntu-24.04
            architecture: x86_64
            distro: Debian
            tool: buildDebian

          - runner: ubuntu-24.04-arm
            architecture: aarch64
            distro: Debian
            dockerSource: balenalib/raspberrypi3-64:{distroVersion}-build
            tool: buildDebian

          - runner: ubuntu-24.04-arm
            architecture: armv6l            
            distro: Debian
            dockerSource: balenalib/raspberry-pi:{distroVersion}-build
            tool: buildDebian

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Set docker meta-data
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/awawa-dev/${{ matrix.architecture }}/${{ matrix.distro }}:${{ matrix.distroVersion }}
          labels: |
            maintainer=HyperHDR
            org.opencontainers.image.title="${{ matrix.distro }} (${{ matrix.distroVersion }})"
            org.opencontainers.image.description="HyperHDR build environment"
            org.opencontainers.image.url="https://hyperhdr.eu"
            org.opencontainers.image.vendor="HyperHDR"
            org.opencontainers.image.licenses="MIT"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push docker container
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: false
          file: ${{ matrix.tool }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
              DOCKER_SOURCE=${{ ${{ matrix.dockerSource }} || "${{ matrix.distro }}:${{ matrix.distroVersion }}" }}